apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "result.fullname" . }}
  labels:
    {{- include "result.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.result.replicaCount }}
  selector:
    matchLabels:
      {{- include "result.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.result.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "result.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.result.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      securityContext:
        {{- toYaml .Values.result.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.result.securityContext | nindent 12 }}
          image: "{{ .Values.result.image.repository }}:{{ .Values.result.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.result.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.result.resources | nindent 12 }}
      {{- with .Values.result.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.result.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.result.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
