apiVersion: v1
kind: Service
metadata:
  name: {{ include "result.fullname" . }}
  labels:
    {{- include "result.labels" . | nindent 4 }}
spec:
  type: {{ .Values.result.service.type }}
  ports:
    - port: {{ .Values.result.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "result.selectorLabels" . | nindent 4 }}
